<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" contents="width=device-width,initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" contents="ie=edge">
	<link rel="stylesheet" href="<?php echo URLROOT; ?>/css/style.css">
	<title><?php echo SITENAME; ?></title>

	<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
</head>
<body>